"""
Django settings for testcanvas_project project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dzi2&4oa*quzhnt=+oxrf5-bwu64jc_%0ee6ayn5qvx=fu6$w*'

# SECURITY WARNING: don't run with debug turned on in production!
# Controlled via the DJANGO_DEBUG environment variable (defaults to True for development).
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes', 'on')

# Hosts allowed to serve the app. Extend via the DJANGO_ALLOWED_HOSTS env var (comma-separated).
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', '[::1]']
_extra_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
if _extra_hosts:
    ALLOWED_HOSTS += [h.strip() for h in _extra_hosts.split(',') if h.strip()]


# MCP observability: maximum number of McpInteractionLog rows to keep.
# Configurable via the MCP_LOG_MAX_ENTRIES environment variable (defaults to
# 1000). Older rows are pruned only when the table grows past this ceiling.
try:
    MCP_LOG_MAX_ENTRIES = int(os.environ.get('MCP_LOG_MAX_ENTRIES', '1000'))
except ValueError:
    MCP_LOG_MAX_ENTRIES = 1000


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'testcanvas.apps.TestcanvasConfig',
    'testcanvas_mcp.apps.TestcanvasMcpConfig',
    # custom for this project
    'rest_framework',
    'mcp_server'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'testcanvas_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Exposes the preferred traceability view (graph vs matrix) so
                # every "Back to traceability" link points to the same place.
                'testcanvas.context_processors.traceability_view',
            ],
        },
    },
]

WSGI_APPLICATION = 'testcanvas_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Authentication redirects
# The landing page (testcanvas:index) doubles as the login screen.
LOGIN_URL = 'testcanvas:index'
LOGIN_REDIRECT_URL = 'testcanvas:map_list'
LOGOUT_REDIRECT_URL = 'testcanvas:index'


# Django REST Framework settings
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly"
    ]
}

# MCP server settings
# Definisci l'endpoint per farlo coincidere con http://ip:xxx/mcp
DJANGO_MCP_ENDPOINT = "mcp" # Raggiungibile su /mcp

# Forza l'endpoint MCP a richiedere l'autenticazione tramite il tuo token
DJANGO_MCP_AUTHENTICATION_CLASSES = [
    'testcanvas_mcp.auth.StaticTokenAuthentication',
]